// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujheeiwuxliclnlkowra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqaGVlaXd1eGxpY2xubGtvd3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2ODYyMDMsImV4cCI6MjA3MjI2MjIwM30.6p4sxBVy0iRRS3Qdzc4R_bT04bizez7Ayhy59jyvl0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});